# Generated by Django 3.1.6 on 2022-08-18 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='balance_money',
            new_name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='bank_acc_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_acc_type',
            field=models.CharField(default='saving', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='user',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization_agent_list',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
