# Generated by Django 3.1.6 on 2022-08-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20220818_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='balance_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
