# Generated by Django 3.2.4 on 2021-06-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('user_name', models.CharField(max_length=34)),
                ('user_photo', models.ImageField(default='images/default_profile_img.jpg', upload_to='images/profileimage/')),
                ('user_type', models.CharField(max_length=20)),
                ('is_agent', models.BooleanField(default=False)),
                ('user_phone', models.IntegerField(null=True)),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
