# Generated by Django 3.1.6 on 2022-08-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_user_profile_wallet_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_org',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_address',
            field=models.CharField(default='default', max_length=122),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_city',
            field=models.CharField(default='default', max_length=122),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_state',
            field=models.CharField(default='default', max_length=122),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user_zipcode',
            field=models.CharField(default='default', max_length=122),
        ),
    ]
