# Generated by Django 3.2.4 on 2021-07-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_lat', models.FloatField()),
                ('device_long', models.FloatField()),
                ('is_active', models.BooleanField(default=False)),
                ('device_mac', models.CharField(default='', max_length=100)),
                ('device_type', models.CharField(max_length=30)),
                ('privlaged_user', models.TextField(null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.agent')),
            ],
        ),
        migrations.CreateModel(
            name='device_type_availaable',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='waterpoint',
            fields=[
                ('wp_id', models.AutoField(primary_key=True, serialize=False)),
                ('water_level', models.FloatField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='washroom',
            fields=[
                ('washroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_urinal', models.IntegerField()),
                ('no_of_pots', models.IntegerField()),
                ('no_of_bath', models.IntegerField()),
                ('urinal_filled', models.IntegerField(null=True)),
                ('pot_filled', models.IntegerField(null=True)),
                ('bath_filled', models.IntegerField(null=True)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
        migrations.CreateModel(
            name='dustbin',
            fields=[
                ('dust_id', models.AutoField(primary_key=True, serialize=False)),
                ('dustbin_level', models.FloatField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
    ]
