# Generated by Django 4.1 on 2022-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20220803_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='supervisor_username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
