# Generated by Django 3.1.6 on 2022-08-18 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='supervisor',
            fields=[
                ('supervisor_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_provider', models.CharField(max_length=30, null=True)),
                ('balance_amount', models.FloatField(default=0)),
                ('bank_acc_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_acc_name', models.CharField(max_length=50)),
                ('bank_ifsc', models.CharField(max_length=20)),
                ('supervisor_is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sup_agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervisor.supervisor')),
            ],
        ),
    ]
