# Generated by Django 4.1 on 2022-08-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0002_auto_20220818_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sup_agent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
