# Generated by Django 4.1 on 2022-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0004_remove_sup_agent_sup_agent_id_sup_agent_agent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sup_agent',
            name='status',
            field=models.CharField(choices=[(0, 'rejected'), (1, 'approved'), (2, 'pending')], default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='organization_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
