# Generated by Django 4.1 on 2022-09-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0005_sup_agent_status_supervisor_organization_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sup_agent',
            old_name='agent_id',
            new_name='agent',
        ),
        migrations.RenameField(
            model_name='sup_agent',
            old_name='supervisor_id',
            new_name='supervisor',
        ),
    ]
